/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.VIEWS;

import com.CONTROLLER.AlunoContr;
import com.CONTROLLER.ProfessorContr;
import com.CONTROLLER.TurmaContr;
import com.DAO.TurmaDao;
import com.Modelos.Professor;
import com.Modelos.Turma;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author IRENE FUTA
 */
public class frmMenuCoordenador extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public ProfessorContr professorContr = new ProfessorContr();
    public TurmaContr turmaContr = new TurmaContr();

    public frmMenuCoordenador() {
        initComponents();
        this.setLocationRelativeTo(null);
        // desblitar todos tabs
        this.Desativar_Todos_Tabs();

        this.DesativaNovoAluno();
        this.Desativar_Professor();
        this.Desativar_Turmas();
        MostrarCombo(jComboBoxTurmaAluno);
        MostrarCombo(jComboBoxTurmasLecionadaProfessor);
        MostrarComboProfessor(PjComboBoxSelProf);
    }

     public String logados;
    public String acessados;

    public frmMenuCoordenador(String logados, String acessados) {
        this.logados = logados;
        this.acessados = acessados;
        
           initComponents();
        this.setLocationRelativeTo(null);
        // desblitar todos tabs
        this.Desativar_Todos_Tabs();

        this.DesativaNovoAluno();
        this.Desativar_Professor();
        this.Desativar_Turmas();
        MostrarCombo(jComboBoxTurmaAluno);
        MostrarCombo(jComboBoxTurmasLecionadaProfessor);
        MostrarComboProfessor(PjComboBoxSelProf);
        
        lblNome.setText(logados);
        lblAcesso.setText("("+acessados+")");
    }

    
    
    public void Desativar_Todos_Tabs() {

        jTabbedPane1Cordm.setEnabledAt(1, false);
        jTabbedPane1Cordm.setEnabledAt(2, false);
        jTabbedPane1Cordm.setEnabledAt(3, false);
        jTabbedPane1Cordm.setEnabledAt(4, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblAcesso = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCProf = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnCadastAluno = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCTurma = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnCusuaro = new javax.swing.JButton();
        jTabbedPane1Cordm = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        btnEliminarAluno = new javax.swing.JButton();
        btnAtualizarAluno = new javax.swing.JButton();
        btnSalvarAluno = new javax.swing.JButton();
        btnNovoAluno = new javax.swing.JButton();
        jComboBoxTurmaAluno = new javax.swing.JComboBox();
        jComboBoxCursoAluno = new javax.swing.JComboBox();
        txtIdeTurmaAluno = new javax.swing.JTextField();
        jComboClasseAluno = new javax.swing.JComboBox();
        jComboBoxGeneroAluno = new javax.swing.JComboBox();
        txtNomeAluno = new javax.swing.JTextField();
        txtNumProcAluno = new javax.swing.JTextField();
        txtNOrdemAluno = new javax.swing.JTextField();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jComboBoxGeneroProf = new javax.swing.JComboBox();
        txtNomeProfessor = new javax.swing.JTextField();
        txtRegistroProfessor = new javax.swing.JTextField();
        btnNovo1 = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        btnAtualizar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jComboBoxTurmasLecionadaProfessor = new javax.swing.JComboBox();
        jComboBoxDisciplinaProfessor = new javax.swing.JComboBox();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        PjComboBoxCurso1 = new javax.swing.JComboBox();
        PjComboBoxSelProf = new javax.swing.JComboBox();
        PtxtNomeTurma = new javax.swing.JTextField();
        PtxtidTurma = new javax.swing.JTextField();
        PtxtIdPonto = new javax.swing.JTextField();
        btnNovo2 = new javax.swing.JButton();
        btnSalvar2 = new javax.swing.JButton();
        btnAtualizar2 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        PjComboBoxClasse1 = new javax.swing.JComboBox();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        Utxtiduser = new javax.swing.JTextField();
        UtxtUsuario = new javax.swing.JTextField();
        UtxtSenha = new javax.swing.JTextField();
        UjComboBoxModoAcesso = new javax.swing.JComboBox();
        UjComboBoxCategoria = new javax.swing.JComboBox();
        btnNovo3 = new javax.swing.JButton();
        btnSalvar3 = new javax.swing.JButton();
        btnAtualizar3 = new javax.swing.JButton();
        btnEliminar3 = new javax.swing.JButton();
        UtxtnovaSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 570));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("--");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/logo.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Sistema de Gestao Academica Módulo Controle de Falta");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)))
                .addGap(482, 482, 482))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 80));

        jPanel2.setBackground(new java.awt.Color(6, 128, 182));

        lblNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Adilson Futa");

        lblAcesso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAcesso.setForeground(new java.awt.Color(255, 255, 255));
        lblAcesso.setText("(Coordenador)");

        jPanel3.setBackground(new java.awt.Color(28, 105, 150));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCProf.setBackground(new java.awt.Color(28, 105, 150));
        btnCProf.setForeground(new java.awt.Color(255, 255, 255));
        btnCProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/user92.png"))); // NOI18N
        btnCProf.setText("CADASTRAR PROFESSOR");
        btnCProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCProfActionPerformed(evt);
            }
        });
        jPanel3.add(btnCProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 40));

        btnConsultar.setBackground(new java.awt.Color(28, 105, 150));
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/search100.png"))); // NOI18N
        btnConsultar.setText("CONSULTAS RÁPIDA");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel3.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 40));

        jButton9.setBackground(new java.awt.Color(28, 105, 150));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/document1.png"))); // NOI18N
        jButton9.setText("LISTAR TURMA");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 40));

        btnCadastAluno.setBackground(new java.awt.Color(28, 105, 150));
        btnCadastAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/add184.png"))); // NOI18N
        btnCadastAluno.setText("CADASTRAR ALUNO");
        btnCadastAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastAlunoActionPerformed(evt);
            }
        });
        jPanel3.add(btnCadastAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 40));

        jButton7.setBackground(new java.awt.Color(28, 105, 150));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/user13.png"))); // NOI18N
        jButton7.setText("LISTAR ALUNO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 40));

        jButton1.setBackground(new java.awt.Color(28, 105, 150));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/home149.png"))); // NOI18N
        jButton1.setText("PAGINA INICIAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 40));

        btnCTurma.setBackground(new java.awt.Color(28, 105, 150));
        btnCTurma.setForeground(new java.awt.Color(255, 255, 255));
        btnCTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/write21.png"))); // NOI18N
        btnCTurma.setText("CADASTRAR TURMA");
        btnCTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTurmaActionPerformed(evt);
            }
        });
        jPanel3.add(btnCTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 40));

        jButton8.setBackground(new java.awt.Color(28, 105, 150));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/user74.png"))); // NOI18N
        jButton8.setText("LISTAR PROFESSOR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 40));

        btnCusuaro.setBackground(new java.awt.Color(28, 105, 150));
        btnCusuaro.setForeground(new java.awt.Color(255, 255, 255));
        btnCusuaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconCoordenador/user7.png"))); // NOI18N
        btnCusuaro.setText("USUARIO");
        btnCusuaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusuaroActionPerformed(evt);
            }
        });
        jPanel3.add(btnCusuaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton10.setBackground(new java.awt.Color(6, 128, 182));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("OK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(6, 128, 182));
        jLabel2.setText("Consultar Por");

        jComboBox1.setForeground(new java.awt.Color(51, 0, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Tabela>", "Aluno", "Professor", "Turma", "Livro Ponto", "Faltas" }));

        jTextField1.setForeground(new java.awt.Color(6, 128, 182));
        jTextField1.setText("digite algo ......");
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(6, 128, 182));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("|<<");

        jButton12.setBackground(new java.awt.Color(6, 128, 182));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("<<");

        jButton13.setBackground(new java.awt.Color(6, 128, 182));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText(">>");

        jButton14.setBackground(new java.awt.Color(6, 128, 182));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText(">|");

        jComboBox2.setForeground(new java.awt.Color(51, 0, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Opção>", "Nome", "Codigo", "Todos" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("", jPanel4);

        jTabbedPane1Cordm.addTab("Consultas", jTabbedPane2);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnEliminarAluno.setBackground(new java.awt.Color(6, 128, 182));
        btnEliminarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarAluno.setText("Eliminar");
        btnEliminarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlunoActionPerformed(evt);
            }
        });

        btnAtualizarAluno.setBackground(new java.awt.Color(6, 128, 182));
        btnAtualizarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarAluno.setText("Atualizar");
        btnAtualizarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarAlunoActionPerformed(evt);
            }
        });

        btnSalvarAluno.setBackground(new java.awt.Color(6, 128, 182));
        btnSalvarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarAluno.setText("Salvar");
        btnSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlunoActionPerformed(evt);
            }
        });

        btnNovoAluno.setBackground(new java.awt.Color(6, 128, 182));
        btnNovoAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoAluno.setText("Novo");
        btnNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAlunoActionPerformed(evt);
            }
        });

        jComboBoxTurmaAluno.setForeground(new java.awt.Color(6, 128, 182));
        jComboBoxTurmaAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Turma>" }));
        jComboBoxTurmaAluno.setBorder(null);

        jComboBoxCursoAluno.setForeground(new java.awt.Color(6, 128, 182));
        jComboBoxCursoAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Curso>", "Informatica", "Informatica Multimedia", " Electronica Telecomunicação", " Electronica Audio e Video" }));
        jComboBoxCursoAluno.setBorder(null);

        txtIdeTurmaAluno.setEditable(false);
        txtIdeTurmaAluno.setForeground(new java.awt.Color(6, 128, 182));
        txtIdeTurmaAluno.setText("Localizar Turma");
        txtIdeTurmaAluno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboClasseAluno.setForeground(new java.awt.Color(6, 128, 182));
        jComboClasseAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Classe>", "10", "11", "12", "13" }));
        jComboClasseAluno.setBorder(null);

        jComboBoxGeneroAluno.setForeground(new java.awt.Color(6, 128, 182));
        jComboBoxGeneroAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Genero>", "Masculino", "Femenino" }));
        jComboBoxGeneroAluno.setBorder(null);

        txtNomeAluno.setForeground(new java.awt.Color(6, 128, 182));
        txtNomeAluno.setText("Digite o Nome do Aluno");
        txtNomeAluno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNomeAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeAlunoMouseClicked(evt);
            }
        });

        txtNumProcAluno.setForeground(new java.awt.Color(6, 128, 182));
        txtNumProcAluno.setText("Digite o numero de Processo");
        txtNumProcAluno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNumProcAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumProcAlunoMouseClicked(evt);
            }
        });

        txtNOrdemAluno.setForeground(new java.awt.Color(6, 128, 182));
        txtNOrdemAluno.setText("Digite o Numero de Ordem");
        txtNOrdemAluno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNOrdemAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNOrdemAlunoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdeTurmaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jComboBoxTurmaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboClasseAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtNomeAluno)
                        .addComponent(jComboBoxGeneroAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(txtNumProcAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNOrdemAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBoxCursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(btnNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSalvarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAtualizarAluno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEliminarAluno)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumProcAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOrdemAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxGeneroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxTurmaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboClasseAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdeTurmaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoAluno)
                    .addComponent(btnSalvarAluno)
                    .addComponent(btnAtualizarAluno)
                    .addComponent(btnEliminarAluno))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("", jPanel9);

        jTabbedPane1Cordm.addTab("Cadastrar Aluno", jTabbedPane3);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxGeneroProf.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxGeneroProf.setForeground(new java.awt.Color(6, 128, 182));
        jComboBoxGeneroProf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Genero>", "Masculino", "Femenino" }));

        txtNomeProfessor.setForeground(new java.awt.Color(6, 128, 182));
        txtNomeProfessor.setText("Digite o Nome do Professor");
        txtNomeProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeProfessorMouseClicked(evt);
            }
        });

        txtRegistroProfessor.setForeground(new java.awt.Color(6, 128, 182));
        txtRegistroProfessor.setText("Digite o Numero de Registro do Professor");
        txtRegistroProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRegistroProfessorMouseClicked(evt);
            }
        });

        btnNovo1.setBackground(new java.awt.Color(6, 128, 182));
        btnNovo1.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo1.setText("Novo");
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });

        btnSalvar1.setBackground(new java.awt.Color(6, 128, 182));
        btnSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        btnAtualizar1.setBackground(new java.awt.Color(6, 128, 182));
        btnAtualizar1.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar1.setText("Atualizar");
        btnAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setBackground(new java.awt.Color(6, 128, 182));
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        jComboBoxTurmasLecionadaProfessor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxTurmasLecionadaProfessor.setForeground(new java.awt.Color(6, 128, 182));
        jComboBoxTurmasLecionadaProfessor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Turma>" }));

        jComboBoxDisciplinaProfessor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxDisciplinaProfessor.setForeground(new java.awt.Color(6, 128, 182));
        jComboBoxDisciplinaProfessor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Disciplina>", "Quimica", "Fisica", "Matematica", "Ingles", "Informatica", "Programação", "Electronica", "Telecomunição", "Tecnologia de Informação e Comunicação", "Educação Fisica" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRegistroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxDisciplinaProfessor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                        .addComponent(jComboBoxGeneroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jComboBoxTurmasLecionadaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(btnNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAtualizar1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminar1))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txtRegistroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jComboBoxDisciplinaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jComboBoxGeneroProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo1)
                            .addComponent(btnSalvar1)
                            .addComponent(btnAtualizar1)
                            .addComponent(btnEliminar1)))
                    .addComponent(jComboBoxTurmasLecionadaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("", jPanel10);

        jTabbedPane1Cordm.addTab("Cadastrar Professor", jTabbedPane4);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        PjComboBoxCurso1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PjComboBoxCurso1.setForeground(new java.awt.Color(6, 128, 182));
        PjComboBoxCurso1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Curso>", "Informatica", "Informatica Multimedia", "Electronica Telecomunicação", "Electronica Audio e Video", "" }));

        PjComboBoxSelProf.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PjComboBoxSelProf.setForeground(new java.awt.Color(6, 128, 182));
        PjComboBoxSelProf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Professor>" }));

        PtxtNomeTurma.setForeground(new java.awt.Color(6, 128, 182));
        PtxtNomeTurma.setText("Digite  a Turma");
        PtxtNomeTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PtxtNomeTurmaMouseClicked(evt);
            }
        });

        PtxtidTurma.setForeground(new java.awt.Color(6, 128, 182));
        PtxtidTurma.setText("Digite o Identificador Turma");
        PtxtidTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PtxtidTurmaMouseClicked(evt);
            }
        });

        PtxtIdPonto.setForeground(new java.awt.Color(6, 128, 182));
        PtxtIdPonto.setText("Digite o Identificador do Livro de Ponto");
        PtxtIdPonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PtxtIdPontoMouseClicked(evt);
            }
        });

        btnNovo2.setBackground(new java.awt.Color(6, 128, 182));
        btnNovo2.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo2.setText("Novo");
        btnNovo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo2ActionPerformed(evt);
            }
        });

        btnSalvar2.setBackground(new java.awt.Color(6, 128, 182));
        btnSalvar2.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar2.setText("Salvar");
        btnSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar2ActionPerformed(evt);
            }
        });

        btnAtualizar2.setBackground(new java.awt.Color(6, 128, 182));
        btnAtualizar2.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar2.setText("Atualizar");
        btnAtualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar2ActionPerformed(evt);
            }
        });

        btnEliminar2.setBackground(new java.awt.Color(6, 128, 182));
        btnEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar2.setText("Eliminar");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        PjComboBoxClasse1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PjComboBoxClasse1.setForeground(new java.awt.Color(6, 128, 182));
        PjComboBoxClasse1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Classe>", "10", "11", "12", "13" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PjComboBoxClasse1, javax.swing.GroupLayout.Alignment.LEADING, 0, 226, Short.MAX_VALUE)
                    .addComponent(PjComboBoxSelProf, javax.swing.GroupLayout.Alignment.LEADING, 0, 226, Short.MAX_VALUE)
                    .addComponent(PtxtIdPonto, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PtxtNomeTurma)
                            .addComponent(PtxtidTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PjComboBoxCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnNovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar2)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PtxtIdPonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PtxtidTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PtxtNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PjComboBoxSelProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PjComboBoxCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PjComboBoxClasse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo2)
                    .addComponent(btnSalvar2)
                    .addComponent(btnAtualizar2)
                    .addComponent(btnEliminar2))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("", jPanel11);

        jTabbedPane1Cordm.addTab("Cadastrar Turma", jTabbedPane5);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Utxtiduser.setForeground(new java.awt.Color(6, 128, 182));
        Utxtiduser.setText("Identificador Usuario");
        Utxtiduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UtxtiduserMouseClicked(evt);
            }
        });
        Utxtiduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtxtiduserActionPerformed(evt);
            }
        });

        UtxtUsuario.setForeground(new java.awt.Color(6, 128, 182));
        UtxtUsuario.setText("Digite o Nome Usuario");
        UtxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UtxtUsuarioMouseClicked(evt);
            }
        });

        UtxtSenha.setForeground(new java.awt.Color(6, 128, 182));
        UtxtSenha.setText("Digite a Senha");
        UtxtSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UtxtSenhaMouseClicked(evt);
            }
        });

        UjComboBoxModoAcesso.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        UjComboBoxModoAcesso.setForeground(new java.awt.Color(6, 128, 182));
        UjComboBoxModoAcesso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Modo Acesso>", "Automatico", "Normal" }));
        UjComboBoxModoAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UjComboBoxModoAcessoActionPerformed(evt);
            }
        });

        UjComboBoxCategoria.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        UjComboBoxCategoria.setForeground(new java.awt.Color(6, 128, 182));
        UjComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleciona Categoria>", "Coordenador", "Professor" }));

        btnNovo3.setBackground(new java.awt.Color(6, 128, 182));
        btnNovo3.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo3.setText("Novo");
        btnNovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo3ActionPerformed(evt);
            }
        });

        btnSalvar3.setBackground(new java.awt.Color(6, 128, 182));
        btnSalvar3.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar3.setText("Salvar");
        btnSalvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar3ActionPerformed(evt);
            }
        });

        btnAtualizar3.setBackground(new java.awt.Color(6, 128, 182));
        btnAtualizar3.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar3.setText("Atualizar");
        btnAtualizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar3ActionPerformed(evt);
            }
        });

        btnEliminar3.setBackground(new java.awt.Color(6, 128, 182));
        btnEliminar3.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar3.setText("Eliminar");
        btnEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar3ActionPerformed(evt);
            }
        });

        UtxtnovaSenha.setForeground(new java.awt.Color(6, 128, 182));
        UtxtnovaSenha.setText("Repita Novamente a Senha");
        UtxtnovaSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UtxtnovaSenhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UtxtUsuario)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                    .addComponent(UtxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(UtxtnovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Utxtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addComponent(UjComboBoxModoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(UjComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnNovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(226, 226, 226))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Utxtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(UtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UtxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UtxtnovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UjComboBoxModoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UjComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo3)
                    .addComponent(btnSalvar3)
                    .addComponent(btnAtualizar3)
                    .addComponent(btnEliminar3))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("", jPanel12);

        jTabbedPane1Cordm.addTab("Usuario ", jTabbedPane6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAcesso)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1Cordm, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblAcesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1Cordm))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 990, 480));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        // new frmPrincipal().setVisible(true);
        new frmPrincipal(logados, acessados).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        this.jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MousePressed

    private void btnEliminarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlunoActionPerformed
        this.DeletarAluno();
    }//GEN-LAST:event_btnEliminarAlunoActionPerformed

    private void btnAtualizarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarAlunoActionPerformed

        // por o id e traz o aluno todo ele.... e atualiza dai
        this.Atualizar_Aluno();
    }//GEN-LAST:event_btnAtualizarAlunoActionPerformed

    public void DeletarAluno() {
        // permitir apenas numero
        if (!txtNumProcAluno.getText().isEmpty()) {
            //int idprocesso = list.get(registroAtual).getProcesso();  // poderia usar esse aqui
            int processo = Integer.parseInt(txtNumProcAluno.getText());
            new AlunoContr().Eliminar(processo);
            JOptionPane.showMessageDialog(this, "Eliminado com Sucesso");
            this.LimparAluno();
        } else {
            JOptionPane.showMessageDialog(this, "Insira o numero Processo");
            this.LimparAluno();
        }
    }

    public void LimparAluno() {

        txtIdeTurmaAluno.setText("");
        txtNOrdemAluno.setText("");
        txtNomeAluno.setText("");
        txtNumProcAluno.setText("");
        jComboBoxCursoAluno.setSelectedIndex(0);
        jComboBoxGeneroAluno.setSelectedIndex(0);
        jComboBoxTurmaAluno.setSelectedIndex(0);;
        jComboClasseAluno.setSelectedIndex(0);

    }

    public boolean VerifcarInPuts() {
        boolean volta = false;
        if ((jComboBoxCursoAluno.getSelectedIndex() != 0 && jComboBoxGeneroAluno.getSelectedIndex() != 0
                && jComboBoxTurmaAluno.getSelectedIndex() != 0 && jComboClasseAluno.getSelectedIndex() != 0)
                || (!txtNOrdemAluno.getText().isEmpty()
                && !txtIdeTurmaAluno.getText().isEmpty()
                && txtNomeAluno.getText().isEmpty() && !txtNumProcAluno.getText().isEmpty())) {
            // esta nao selecionado volta true
            return volta = true;
        }
        return volta;
    }

    public void MostrarCombo(JComboBox box) {
        ArrayList<Turma> array = new TurmaDao().listagem();
        String str = null;
        for (Turma array1 : array) {
            str = array1.getNome();
            box.addItem(str);
        }
    }

    public void MostrarComboProfessor(JComboBox box) {
        ArrayList<Professor> array = professorContr.ListaGeral();
        String str = null;
        for (Professor array1 : array) {
            str = array1.getNome();
            box.addItem(str);
        }
    }

    public void SalvarAluno() {
        if (VerifcarInPuts() == true) {

            int idturma = new TurmaContr().PegaIdTurma_aPArtirNome(jComboBoxTurmaAluno.getSelectedItem().toString());
            txtIdeTurmaAluno.setText(String.valueOf(idturma));
            int classe = Integer.parseInt(jComboClasseAluno.getSelectedItem().toString());
            String turma = jComboBoxTurmaAluno.getSelectedItem().toString();
            String curso = jComboBoxCursoAluno.getSelectedItem().toString();
            String nome = txtNomeAluno.getText();
            String genero = jComboBoxGeneroAluno.getSelectedItem().toString();
            int numAluno = Integer.parseInt(txtNOrdemAluno.getText());
            int processo = Integer.parseInt(txtNumProcAluno.getText());

            new AlunoContr().Salvar(idturma, genero, numAluno, processo, nome, classe, turma, curso);
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso");
            this.LimparAluno();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione: 1-)Curso 2-)Genero 3-)Turma \n Preencha Todos os Campos...");
            this.LimparAluno();
        }

    }

    public void Atualizar_Aluno() {
        if (VerifcarInPuts() == true) {

            int idturma = new TurmaContr().PegaIdTurma_aPArtirNome(jComboBoxTurmaAluno.getSelectedItem().toString());
            txtIdeTurmaAluno.setText(String.valueOf(idturma));
            int classe = Integer.parseInt(jComboClasseAluno.getSelectedItem().toString());
            String turma = jComboBoxTurmaAluno.getSelectedItem().toString();
            String curso = jComboBoxCursoAluno.getSelectedItem().toString();
            String nome = txtNomeAluno.getText();
            String genero = jComboBoxGeneroAluno.getSelectedItem().toString();
            int numAluno = Integer.parseInt(txtNOrdemAluno.getText());
            int processo = Integer.parseInt(txtNumProcAluno.getText());

            new AlunoContr().Alterar(idturma, genero, numAluno, processo, nome, classe, turma, curso);
            JOptionPane.showMessageDialog(this, "Atualizado com Sucesso");
            this.LimparAluno();
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorio...");
            this.LimparAluno();
        }

    }

    private void btnSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlunoActionPerformed
        this.SalvarAluno();
    }//GEN-LAST:event_btnSalvarAlunoActionPerformed

    public void NovoAluno() {
        boolean b = true;
        txtIdeTurmaAluno.setEnabled(b);
        txtNOrdemAluno.setEnabled(b);
        txtNomeAluno.setEnabled(b);
        txtNumProcAluno.setEnabled(b);
        jComboBoxCursoAluno.setEnabled(b);
        jComboBoxGeneroAluno.setEnabled(b);
        jComboBoxTurmaAluno.setEnabled(b);
        jComboClasseAluno.setEnabled(b);
    }

    public void DesativaNovoAluno() {
        boolean b = false;
        txtIdeTurmaAluno.setEnabled(b);
        txtNOrdemAluno.setEnabled(b);
        txtNomeAluno.setEnabled(b);
        txtNumProcAluno.setEnabled(b);
        jComboBoxCursoAluno.setEnabled(b);
        jComboBoxGeneroAluno.setEnabled(b);
        jComboBoxTurmaAluno.setEnabled(b);
        jComboClasseAluno.setEnabled(b);
    }

    private void btnNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAlunoActionPerformed
        this.NovoAluno();
    }//GEN-LAST:event_btnNovoAlunoActionPerformed

    public void Ativar_Professor() {
        boolean b = true;
        jComboBoxDisciplinaProfessor.setEnabled(b);
        jComboBoxGeneroProf.setEnabled(b);
        jComboBoxTurmasLecionadaProfessor.setEnabled(b);
        txtNomeProfessor.setEnabled(b);
        txtRegistroProfessor.setEnabled(b);
    }

    public void Desativar_Professor() {
        boolean b = false;
        jComboBoxDisciplinaProfessor.setEnabled(b);
        jComboBoxGeneroProf.setEnabled(b);
        jComboBoxTurmasLecionadaProfessor.setEnabled(b);
        txtNomeProfessor.setEnabled(b);
        txtRegistroProfessor.setEnabled(b);
    }

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        // novo professor
        Ativar_Professor();

    }//GEN-LAST:event_btnNovo1ActionPerformed

    public boolean VerifcarInPutProfessor() {
        boolean volta = false;
        if ((jComboBoxDisciplinaProfessor.getSelectedIndex() != 0 && jComboBoxGeneroProf.getSelectedIndex() != 0
                && jComboBoxTurmasLecionadaProfessor.getSelectedIndex() != 0)
                || (!txtNomeProfessor.getText().isEmpty()
                && !txtRegistroProfessor.getText().isEmpty())) {
            // esta nao selecionado volta true
            return volta = true;
        }
        return volta;
    }

    public void SalvarProfessor() {

        try {
            if (VerifcarInPutProfessor() == true) {

                int nregistro = Integer.parseInt(txtRegistroProfessor.getText());
                String nome = txtNomeProfessor.getText();
                String disciplinas = jComboBoxDisciplinaProfessor.getSelectedItem().toString();
                String tumas_de_aula = jComboBoxTurmasLecionadaProfessor.getSelectedItem().toString();
                String genero = jComboBoxGeneroProf.getSelectedItem().toString();

                professorContr.Salvar(nregistro, nome, disciplinas, tumas_de_aula, genero);

                JOptionPane.showMessageDialog(this, "Guardado Com Sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, " Preencha Todos os Campos...");
                this.LimparAluno();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nao foi Possivel SALVAR" + e.getLocalizedMessage());
        }

    }
    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        SalvarProfessor();
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    public void AtualizarProfessor() {
        try {
            if (VerifcarInPutProfessor() == true) {

                int nregistro = Integer.parseInt(txtRegistroProfessor.getText());
                String nome = txtNomeProfessor.getText();
                String disciplinas = jComboBoxDisciplinaProfessor.getSelectedItem().toString();
                String tumas_de_aula = jComboBoxTurmasLecionadaProfessor.getSelectedItem().toString();
                String genero = jComboBoxGeneroProf.getSelectedItem().toString();

                professorContr.Alterar(nregistro, nome, disciplinas, tumas_de_aula, genero);

                JOptionPane.showMessageDialog(this, "Atualizado Com Sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, " Preencha Todos os Campos...");
                this.LimparAluno();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nao foi Possivel Alterar" + e.getLocalizedMessage());
        }
    }

    private void btnAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar1ActionPerformed
        this.AtualizarProfessor();
    }//GEN-LAST:event_btnAtualizar1ActionPerformed

    public void EliminarProf() {
        int v;
        if (!txtRegistroProfessor.getText().isEmpty()) {
            v = Integer.parseInt(txtRegistroProfessor.getText());
            professorContr.Eliminar(v);
            JOptionPane.showMessageDialog(this, "Eliminado com Sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Insira o numero Processo");
        }
    }

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        this.EliminarProf();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    public void Ativar_Turmas() {
        boolean b = true;
        PtxtIdPonto.setEnabled(b);
        PjComboBoxClasse1.setEnabled(b);
        PjComboBoxCurso1.setEnabled(b);
        PjComboBoxSelProf.setEnabled(b);
        PtxtNomeTurma.setEnabled(b);
        PtxtidTurma.setEnabled(b);
    }

    public void Desativar_Turmas() {
        boolean b = false;
        PtxtIdPonto.setEnabled(b);
        PjComboBoxClasse1.setEnabled(b);
        PjComboBoxCurso1.setEnabled(b);
        PjComboBoxSelProf.setEnabled(b);
        PtxtNomeTurma.setEnabled(b);
        PtxtidTurma.setEnabled(b);
    }
    private void btnNovo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo2ActionPerformed
        Ativar_Turmas();
    }//GEN-LAST:event_btnNovo2ActionPerformed

    public void SalvarTurmas() {

        int classe = Integer.parseInt(PjComboBoxClasse1.getSelectedItem().toString());
        String curso = PjComboBoxCurso1.getSelectedItem().toString();
        String nomeProf = PjComboBoxSelProf.getSelectedItem().toString();
        int idProf = professorContr.BuscaComum(nomeProf).getNregistro();
        int idPonto = Integer.parseInt(PtxtIdPonto.getText());
        String nomeTurma = PtxtNomeTurma.getText();
        int idTurma = Integer.parseInt(PtxtidTurma.getText());

        turmaContr.Salvar(idTurma, idPonto, idProf, nomeTurma, classe, curso);

    }

    private void btnSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar2ActionPerformed
        this.SalvarTurmas();
    }//GEN-LAST:event_btnSalvar2ActionPerformed

    public void Atualizar_Turmas() {

        int classe = Integer.parseInt(PjComboBoxClasse1.getSelectedItem().toString());
        String curso = PjComboBoxCurso1.getSelectedItem().toString();
        String nomeProf = PjComboBoxSelProf.getSelectedItem().toString();
        int idProf = professorContr.BuscaComum(nomeProf).getNregistro();
        int idPonto = Integer.parseInt(PtxtIdPonto.getText());
        String nomeTurma = PtxtNomeTurma.getText();
        int idTurma = Integer.parseInt(PtxtidTurma.getText());

        turmaContr.Alterar(idTurma, idPonto, idProf, nomeTurma, classe, curso);

    }
    private void btnAtualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar2ActionPerformed
        this.Atualizar_Turmas();
    }//GEN-LAST:event_btnAtualizar2ActionPerformed
    public void Eliminjar_Turmas() {

        if (!PtxtidTurma.getText().isEmpty()) {
            int idTurma = Integer.parseInt(PtxtidTurma.getText());
            turmaContr.Eliminar(idTurma);
            JOptionPane.showMessageDialog(this, "Eliminado com Sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Insira o Codigo da Turma");
        }

    }
    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        this.Eliminjar_Turmas();
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void UtxtiduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtxtiduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UtxtiduserActionPerformed

    private void UjComboBoxModoAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UjComboBoxModoAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UjComboBoxModoAcessoActionPerformed

    private void btnNovo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovo3ActionPerformed

    private void btnSalvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar3ActionPerformed

    private void btnAtualizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizar3ActionPerformed

    private void btnEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar3ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        jTabbedPane1Cordm.setSelectedIndex(0);
        jTabbedPane1Cordm.setEnabledAt(0, true);
        jTabbedPane1Cordm.setEnabledAt(1, false);
        jTabbedPane1Cordm.setEnabledAt(2, false);
        jTabbedPane1Cordm.setEnabledAt(3, false);
        jTabbedPane1Cordm.setEnabledAt(4, false);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnCadastAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastAlunoActionPerformed
        jTabbedPane1Cordm.setSelectedIndex(1);
        jTabbedPane1Cordm.setEnabledAt(0, false);
        jTabbedPane1Cordm.setEnabledAt(1, true);
        jTabbedPane1Cordm.setEnabledAt(2, false);
        jTabbedPane1Cordm.setEnabledAt(3, false);
        jTabbedPane1Cordm.setEnabledAt(4, false);
    }//GEN-LAST:event_btnCadastAlunoActionPerformed

    private void btnCProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCProfActionPerformed
        jTabbedPane1Cordm.setSelectedIndex(2);
        jTabbedPane1Cordm.setEnabledAt(0, false);
        jTabbedPane1Cordm.setEnabledAt(1, false);
        jTabbedPane1Cordm.setEnabledAt(2, true);
        jTabbedPane1Cordm.setEnabledAt(3, false);
        jTabbedPane1Cordm.setEnabledAt(4, false);
    }//GEN-LAST:event_btnCProfActionPerformed

    private void btnCTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTurmaActionPerformed
        jTabbedPane1Cordm.setSelectedIndex(3);
        jTabbedPane1Cordm.setEnabledAt(0, false);
        jTabbedPane1Cordm.setEnabledAt(1, false);
        jTabbedPane1Cordm.setEnabledAt(2, false);
        jTabbedPane1Cordm.setEnabledAt(3, true);
        jTabbedPane1Cordm.setEnabledAt(4, false);
    }//GEN-LAST:event_btnCTurmaActionPerformed

    private void btnCusuaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusuaroActionPerformed
        jTabbedPane1Cordm.setSelectedIndex(4);
        jTabbedPane1Cordm.setEnabledAt(0, false);
        jTabbedPane1Cordm.setEnabledAt(1, false);
        jTabbedPane1Cordm.setEnabledAt(2, false);
        jTabbedPane1Cordm.setEnabledAt(3, false);
        jTabbedPane1Cordm.setEnabledAt(4, true);
    }//GEN-LAST:event_btnCusuaroActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new frmListarAluno().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new frmListarProfessor().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new frmListarTurma().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtNumProcAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumProcAlunoMouseClicked
        this.txtNumProcAluno.setText("");
    }//GEN-LAST:event_txtNumProcAlunoMouseClicked

    private void txtNOrdemAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNOrdemAlunoMouseClicked
        txtNOrdemAluno.setText("");
    }//GEN-LAST:event_txtNOrdemAlunoMouseClicked

    private void txtNomeAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeAlunoMouseClicked
        txtNomeAluno.setText("");
    }//GEN-LAST:event_txtNomeAlunoMouseClicked

    private void txtRegistroProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistroProfessorMouseClicked
        txtRegistroProfessor.setText("");
    }//GEN-LAST:event_txtRegistroProfessorMouseClicked

    private void txtNomeProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeProfessorMouseClicked
        txtNomeProfessor.setText("");
    }//GEN-LAST:event_txtNomeProfessorMouseClicked

    private void PtxtIdPontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PtxtIdPontoMouseClicked
        PtxtIdPonto.setText("");
    }//GEN-LAST:event_PtxtIdPontoMouseClicked

    private void PtxtidTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PtxtidTurmaMouseClicked
        PtxtidTurma.setText("");
     }//GEN-LAST:event_PtxtidTurmaMouseClicked

    private void PtxtNomeTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PtxtNomeTurmaMouseClicked
        PtxtNomeTurma.setText("");
    }//GEN-LAST:event_PtxtNomeTurmaMouseClicked

    private void UtxtiduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UtxtiduserMouseClicked
        Utxtiduser.setText("");
    }//GEN-LAST:event_UtxtiduserMouseClicked

    private void UtxtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UtxtUsuarioMouseClicked
        UtxtUsuario.setText("");
    }//GEN-LAST:event_UtxtUsuarioMouseClicked

    private void UtxtSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UtxtSenhaMouseClicked
        UtxtSenha.setText("");
    }//GEN-LAST:event_UtxtSenhaMouseClicked

    private void UtxtnovaSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UtxtnovaSenhaMouseClicked
        UtxtnovaSenha.setText("");
    }//GEN-LAST:event_UtxtnovaSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuCoordenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PjComboBoxClasse1;
    private javax.swing.JComboBox PjComboBoxCurso1;
    private javax.swing.JComboBox PjComboBoxSelProf;
    private javax.swing.JTextField PtxtIdPonto;
    private javax.swing.JTextField PtxtNomeTurma;
    private javax.swing.JTextField PtxtidTurma;
    private javax.swing.JComboBox UjComboBoxCategoria;
    private javax.swing.JComboBox UjComboBoxModoAcesso;
    private javax.swing.JTextField UtxtSenha;
    private javax.swing.JTextField UtxtUsuario;
    private javax.swing.JTextField Utxtiduser;
    private javax.swing.JTextField UtxtnovaSenha;
    private javax.swing.JButton btnAtualizar1;
    private javax.swing.JButton btnAtualizar2;
    private javax.swing.JButton btnAtualizar3;
    private javax.swing.JButton btnAtualizarAluno;
    private javax.swing.JButton btnCProf;
    private javax.swing.JButton btnCTurma;
    private javax.swing.JButton btnCadastAluno;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCusuaro;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnEliminar3;
    private javax.swing.JButton btnEliminarAluno;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnNovo2;
    private javax.swing.JButton btnNovo3;
    private javax.swing.JButton btnNovoAluno;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnSalvar2;
    private javax.swing.JButton btnSalvar3;
    private javax.swing.JButton btnSalvarAluno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxCursoAluno;
    private javax.swing.JComboBox jComboBoxDisciplinaProfessor;
    private javax.swing.JComboBox jComboBoxGeneroAluno;
    private javax.swing.JComboBox jComboBoxGeneroProf;
    private javax.swing.JComboBox jComboBoxTurmaAluno;
    private javax.swing.JComboBox jComboBoxTurmasLecionadaProfessor;
    private javax.swing.JComboBox jComboClasseAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1Cordm;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAcesso;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtIdeTurmaAluno;
    private javax.swing.JTextField txtNOrdemAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNomeProfessor;
    private javax.swing.JTextField txtNumProcAluno;
    private javax.swing.JTextField txtRegistroProfessor;
    // End of variables declaration//GEN-END:variables
}
