/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.VIEWS;

import com.CONTROLLER.AlunoContr;
import com.CONTROLLER.OperacaoGeral;
import com.CONTROLLER.TurmaContr;
import com.Modelos.Aluno;
import com.Modelos.Turma;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author IRENE FUTA
 */
public class frmProfessor extends javax.swing.JFrame {

    public OperacaoGeral operacaoGeral=new OperacaoGeral();
   
   
    
    public frmProfessor() {
        initComponents();
         this.setLocationRelativeTo(null);
        ListaPresente.setVisible(false);
        ListaAusente.setVisible(false);
    }

    public String logados;
    public String acessados;

    public frmProfessor(String logados, String acessados)
    {
        this.logados = logados;
        this.acessados = acessados;
       
        
        initComponents();
         this.setLocationRelativeTo(null);
         DestivarTodosTabsContProfs();
         
        ListaPresente.setVisible(false);
        ListaAusente.setVisible(false);
        
        lblNome.setText(this.logados);
        lblAcesso.setText("("+this.acessados+")");
        operacaoGeral.MostrarCombo(LjComboBoxTurmaLivroPonto);
        operacaoGeral.MostrarCombo(jComboBoxTableas);
   }
    
   public void DestivarTodosTabsContProfs() {
        jTabbedPane1Principal.setEnabledAt(0, false);
        jTabbedPane1Principal.setEnabledAt(1, false);
        jTabbedPane1Principal.setEnabledAt(2, false);
        jTabbedPane1Principal.setEnabledAt(3, false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblAcesso = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnConsultaRapida = new javax.swing.JButton();
        btnLivroPonto = new javax.swing.JButton();
        btnQualificarAluno = new javax.swing.JButton();
        btnListarAluno = new javax.swing.JButton();
        btnAvaliarAluno = new javax.swing.JButton();
        jTabbedPane1Principal = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTableas = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        LjComboBoxTurmaLivroPonto = new javax.swing.JComboBox();
        LjComboBox4 = new javax.swing.JComboBox();
        LjTextField2 = new javax.swing.JTextField();
        LjTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        LjComboBox7 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaPresente = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaAusente = new javax.swing.JList();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel16 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("--");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/logo.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Sistema de Gestao Academica Módulo Controle de Falta");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)))
                .addGap(482, 482, 482))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 80));

        jPanel2.setBackground(new java.awt.Color(6, 128, 182));

        lblNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Adilson Futa");

        lblAcesso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAcesso.setForeground(new java.awt.Color(255, 255, 255));
        lblAcesso.setText("(Professor)");

        jPanel3.setBackground(new java.awt.Color(28, 105, 150));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(28, 105, 150));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconProfessor/home149.png"))); // NOI18N
        jButton1.setText("PAGINA INICIAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 5, 240, 40));

        btnConsultaRapida.setBackground(new java.awt.Color(28, 105, 150));
        btnConsultaRapida.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconProfessor/search100.png"))); // NOI18N
        btnConsultaRapida.setText("CONSULTA RÁPIDA");
        btnConsultaRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaRapidaActionPerformed(evt);
            }
        });
        jPanel3.add(btnConsultaRapida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 40));

        btnLivroPonto.setBackground(new java.awt.Color(28, 105, 150));
        btnLivroPonto.setForeground(new java.awt.Color(255, 255, 255));
        btnLivroPonto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconProfessor/open-book.png"))); // NOI18N
        btnLivroPonto.setText("LIVRO PONTO");
        btnLivroPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroPontoActionPerformed(evt);
            }
        });
        jPanel3.add(btnLivroPonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 40));

        btnQualificarAluno.setBackground(new java.awt.Color(28, 105, 150));
        btnQualificarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnQualificarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconProfessor/stats-bars.png"))); // NOI18N
        btnQualificarAluno.setText("QUALIFICAR ALUNO");
        btnQualificarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQualificarAlunoActionPerformed(evt);
            }
        });
        jPanel3.add(btnQualificarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 40));

        btnListarAluno.setBackground(new java.awt.Color(28, 105, 150));
        btnListarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnListarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconProfessor/user13.png"))); // NOI18N
        btnListarAluno.setText("LISTAR ALUNO");
        btnListarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAlunoActionPerformed(evt);
            }
        });
        jPanel3.add(btnListarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 40));

        btnAvaliarAluno.setBackground(new java.awt.Color(28, 105, 150));
        btnAvaliarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjts/iconProfessor/analysis5.png"))); // NOI18N
        btnAvaliarAluno.setText("AVALIAR ALUNO");
        btnAvaliarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarAlunoActionPerformed(evt);
            }
        });
        jPanel3.add(btnAvaliarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 40));

        jTabbedPane1Principal.setForeground(new java.awt.Color(6, 128, 182));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton10.setBackground(new java.awt.Color(6, 128, 182));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("OK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Consultar Por");

        jComboBoxTableas.setForeground(new java.awt.Color(51, 0, 255));
        jComboBoxTableas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Tabela>", "Aluno", "Professor", "Turma", "Livro Ponto", "Faltas" }));

        jTextField1.setForeground(new java.awt.Color(51, 0, 255));
        jTextField1.setText("digite algo ......");
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(6, 128, 182));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("|<<");

        jButton12.setBackground(new java.awt.Color(6, 128, 182));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("<<");

        jButton13.setBackground(new java.awt.Color(6, 128, 182));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText(">>");

        jButton14.setBackground(new java.awt.Color(6, 128, 182));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText(">|");

        jComboBox2.setForeground(new java.awt.Color(51, 0, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Opção>", "Nome", "Codigo", "Todos" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTableas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTableas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("", jPanel4);

        jTabbedPane1Principal.addTab("Consultas", jTabbedPane2);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel5.setBackground(new java.awt.Color(212, 229, 236));

        LjComboBoxTurmaLivroPonto.setForeground(new java.awt.Color(6, 128, 182));
        LjComboBoxTurmaLivroPonto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<TURMA>" }));

        LjComboBox4.setForeground(new java.awt.Color(6, 128, 182));
        LjComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<DISCIPLINA>", "Quimica", "Fisica", "Matematica", "Ingles", "Informatica", "Programação", "Electronica", "Telecomunição", "Tecnologia de Informação e Comunicação", "Educação Fisica" }));

        LjTextField2.setForeground(new java.awt.Color(6, 128, 182));
        LjTextField2.setText("SUMARIO");
        LjTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LjTextField2MouseClicked(evt);
            }
        });
        LjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LjTextField2ActionPerformed(evt);
            }
        });

        LjTextField3.setForeground(new java.awt.Color(6, 128, 182));
        LjTextField3.setText("ASSINATURA");
        LjTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LjTextField3MouseClicked(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(6, 128, 182));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("INICIAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        LjComboBox7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        LjComboBox7.setForeground(new java.awt.Color(6, 128, 182));
        LjComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<CLASSE>", "10", "11", "12", "13" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LjComboBoxTurmaLivroPonto, 0, 109, Short.MAX_VALUE)
                    .addComponent(LjComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(LjComboBox4, 0, 222, Short.MAX_VALUE)
                    .addComponent(LjTextField2)
                    .addComponent(LjTextField3))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LjComboBoxTurmaLivroPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LjComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LjComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        ListaPresente.setBackground(new java.awt.Color(255, 255, 255));
        ListaPresente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        ListaPresente.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Nº-------Processo-------Nome-------Estado" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaPresente);

        ListaAusente.setBackground(new java.awt.Color(255, 255, 255));
        ListaAusente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        ListaAusente.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Nº-------Processo-------Nome-------Estado" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ListaAusente);

        jButton8.setBackground(new java.awt.Color(6, 128, 182));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Anular Falta");

        jButton9.setBackground(new java.awt.Color(6, 128, 182));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Iniciar Chamada");

        jButton15.setBackground(new java.awt.Color(6, 128, 182));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Terminar Chamada");

        jButton16.setBackground(new java.awt.Color(6, 128, 182));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Marcar Falta");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton9)
                                .addGap(33, 33, 33)
                                .addComponent(jButton15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jTabbedPane3.addTab("", jPanel12);

        jTabbedPane1Principal.addTab("Livro Ponto", jTabbedPane3);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("", jPanel16);

        jTabbedPane1Principal.addTab("Listar Aluno", jTabbedPane5);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("", jPanel15);

        jTabbedPane1Principal.addTab("Avaliar Aluno", jTabbedPane6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1Principal)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAcesso)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblAcesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1Principal))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 990, 540));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          dispose();
      // new frmPrincipal().setVisible(true);
       new frmPrincipal(logados, acessados).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
          this.jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MousePressed

    private void btnQualificarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQualificarAlunoActionPerformed
      // dispose();
       new frmEstatistica(logados, acessados).setVisible(true);
    }//GEN-LAST:event_btnQualificarAlunoActionPerformed

    private void LjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LjTextField2ActionPerformed

    void Desativar_todosmambos(){
     boolean b=false;
        LjComboBox4.setEnabled(b);
        LjComboBox7.setEnabled(b);
        LjComboBoxTurmaLivroPonto.setEnabled(b);
        LjTextField2.setEnabled(b);
        LjTextField3.setEnabled(b);
    }
    
    public void preenche_ListadosPresente()
    {
        /*
         String nome_turma=jComboBox1.getSelectedItem().toString();
       nomes = new AlunoContr().ListadeAlunosde_turma(nome_turma); 
        
       DefaultListModel model = new DefaultListModel();
        Lista_aUSENTES.setModel(model);
        Lista_Todos_na_tURMA.setModel(model);
        
        model.clear();
       String s = null;
        
        for (Aluno nome : nomes) {
             Lista_Todos_na_tURMA.setModel(model);
             s = String.valueOf(nome.getNumAluno()).toString() + "----" + nome.getNome().toString();
            model.addElement(s);
        }
        Lista_Todos_na_tURMA.setEnabled(false);
  */
       ArrayList<Aluno> alunos ;
        alunos=new AlunoContr().ListadeAlunosde_turma(LjComboBoxTurmaLivroPonto.getSelectedItem().toString());
        DefaultListModel listModel=new DefaultListModel();
        ListaPresente.setModel(listModel);
        listModel.clear();
       
        String modelo="Nº-------Processo-------Nome-------Estado";
        listModel.addElement(modelo);
        
        String estado="Presente"; // inicialmente presente clicado ausente
        
         String valores=null;
        for (Aluno aluno : alunos) {
        ListaPresente.setModel(listModel);
          valores=String.valueOf(aluno.getNumAluno())+"        "
         +String.valueOf(aluno.getProcesso())+"        "+aluno.getNome()+"        "+estado;
          listModel.addElement(valores);
        }
      
    
    
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      
       // desativar tudo e 
      Desativar_todosmambos();
      //chama lista de faltas
        ListaPresente.setVisible(true);
        ListaAusente.setVisible(true);
        
        //preenche Lista dos Presente
        this.preenche_ListadosPresente();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnConsultaRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaRapidaActionPerformed
        jTabbedPane1Principal.setSelectedIndex(0); 
        jTabbedPane1Principal.setEnabledAt(0, true);
        jTabbedPane1Principal.setEnabledAt(1, false);
        jTabbedPane1Principal.setEnabledAt(2, false);
        jTabbedPane1Principal.setEnabledAt(3, false);
        
    }//GEN-LAST:event_btnConsultaRapidaActionPerformed

    private void btnLivroPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroPontoActionPerformed
        jTabbedPane1Principal.setSelectedIndex(1);
        jTabbedPane1Principal.setEnabledAt(0, false);
        jTabbedPane1Principal.setEnabledAt(1, true);
        jTabbedPane1Principal.setEnabledAt(2, false);
        jTabbedPane1Principal.setEnabledAt(3, false);
    }//GEN-LAST:event_btnLivroPontoActionPerformed

    private void btnListarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAlunoActionPerformed
       jTabbedPane1Principal.setSelectedIndex(2);
        jTabbedPane1Principal.setEnabledAt(0, false);
        jTabbedPane1Principal.setEnabledAt(1, false);
        jTabbedPane1Principal.setEnabledAt(2, true);
        jTabbedPane1Principal.setEnabledAt(3, false);
       
    }//GEN-LAST:event_btnListarAlunoActionPerformed

    private void btnAvaliarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarAlunoActionPerformed
       jTabbedPane1Principal.setSelectedIndex(3);
        jTabbedPane1Principal.setEnabledAt(0, false);
        jTabbedPane1Principal.setEnabledAt(1, false);
        jTabbedPane1Principal.setEnabledAt(2, false);
        jTabbedPane1Principal.setEnabledAt(3, true);
    }//GEN-LAST:event_btnAvaliarAlunoActionPerformed

    private void LjTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LjTextField2MouseClicked
     if(!LjTextField2.getText().isEmpty())
     LjTextField2.setText("");
    }//GEN-LAST:event_LjTextField2MouseClicked

    private void LjTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LjTextField3MouseClicked
     if(!LjTextField3.getText().isEmpty())
     LjTextField3.setText("");
    }//GEN-LAST:event_LjTextField3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaAusente;
    private javax.swing.JList ListaPresente;
    private javax.swing.JComboBox LjComboBox4;
    private javax.swing.JComboBox LjComboBox7;
    private javax.swing.JComboBox LjComboBoxTurmaLivroPonto;
    private javax.swing.JTextField LjTextField2;
    private javax.swing.JTextField LjTextField3;
    private javax.swing.JButton btnAvaliarAluno;
    private javax.swing.JButton btnConsultaRapida;
    private javax.swing.JButton btnListarAluno;
    private javax.swing.JButton btnLivroPonto;
    private javax.swing.JButton btnQualificarAluno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxTableas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1Principal;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAcesso;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
